export * as userModel from "./user.model";
export * as bookModel from "./book.model";
export * as bookAuthorModel from "./book/bookAuthor.model";
export * as bookCategoryModel from "./book/bookCategory.model";
export * as bookImageModel from "./book/bookImage.model";
export * as bookPublisherModel from "./book/bookPublisher.model";
export * as bookTagModel from "./book/bookTag.model";
// export * as bookCopyModel from "./bookCopy.model";
export * as borrowModel from "./borrow.model";
export * as borrowDetailModel from "./borrowDetail.model";
export * as borrowCartModel from "./borrowCart.model";
export * as bannerModel from "./banner.model";
export * as settingsModel from "./settings.model";
export * as newsModel from "./news.model";
export * as eventsModel from "./events.model";
